messages:
  help:
    - "&6TerraDiscovery -- Aide"
    - "&aAliase : /td"
    - " "
    - "&7&l➤ &b/tda reload &f: &7Recharger la configuration "
    - "&7&l➤ &b/tda create <nom> &f: &7Créer une nouvelle zone à votre position"
    - "&7&l➤ &b/tda remove <nom> &: &7Supprimer une zone"
    - "&7&l➤ &b/tda setspawn <nom> &f: &7Définir la position d'une zone"
    - "&7&l➤ &b/tda list &f: &7Voir la liste des zones à découvrir et voir leurs configuration"
    - " "
  warps:
    added:
      - "&7&l&7&l➤ &bVous avez créé le warp &7%warp_name% &b!"
    unlocked:
      - "&e&l⚡ &b&lPLAY.TERRACRAFT.FR &e&l⚡"
      - " "
      - "&e&l✪ &7&lNouvelle zone débloquée ! &e&l✪"
      - "&7➤ &bFéliciation ! Vous avez débloqué une nouvelle zone !"
      - "&7➤ &bvous pouvez y accèder grâce à /warps !"
      - "&a&oVisitez notre boutique /credits pour débloquer tous les warps"
      - " "
    locked:
      - "&e&l⚡ &b&lPLAY.TERRACRAFT.FR &e&l⚡"
      - "&cTu n'as pas encore débloqué cette zone !"
      - "&cExplore le spawn de TerraCraft pour la découvrir"
      - "&eOu débloque tous les warps avec /credit !"
      - " "
    alreadyExist: "&cErreur, cette zone existe déjà !"


titles:
  unlocked:
    firstLine: "&e&lNouvelle zone débloquée !"
    secondLine: "&fVous avez débloqué la zone : %warpDisplayName%"


warps:
  #test:
  #  display-name: "Test"
  #  permission: warps.test
  #  region: test_rg #The WorldGuard region name
  #  cooldown: 5 # Time in second
  #  x:
  #  y:
  #  z:
  #  pitch:
  #  yaw: